/** GENERATED by scripts/acquire/promote-kids-media.ts. Do not hand-edit. */
import type { KidsVideo } from "@/visual-golden/services/kids-media/types";

export const APPROVED_YOUTUBE_KIDS_VIDEOS: KidsVideo[] = [];
