import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const CANDIDATES = resolve(root, "data-sources/kids/youtube/candidates.generated.json");
const APPROVALS = resolve(root, "data-sources/kids/youtube/approvals.json");
const OUT = resolve(root, "client/src/visual-golden/data/kids-youtube-approved.generated.ts");

type ReviewState = "approved" | "rejected" | "pending";

type Approval = {
  providerVideoId: string;
  contentReview: ReviewState;
  depictionReview: ReviewState;
  ageReview: ReviewState;
  rightsReview: ReviewState;
  titleAr: string;
  ageMin?: number;
  ageMax?: number;
  reviewEvidenceUrl: string;
  reviewerId: string;
  reviewedAt: string;
};

type Candidate = {
  id: string;
  provider: "youtube";
  providerVideoId: string;
  publisherName: string;
  publisherChannelId: string;
  titleOriginal: string;
  description: string;
  thumbnailUrl: string;
  topic: string;
  language: string;
  durationSeconds: number | null;
  captionsAvailable: boolean;
  embeddable: boolean;
  sourceUrl: string;
  publishedAt: string | null;
  tags: string[];
};

function fail(message: string): never {
  console.error("promote-kids-media FAILED:", message);
  process.exit(1);
}

function readJson<T>(path: string): T {
  try {
    return JSON.parse(readFileSync(path, "utf-8")) as T;
  } catch (error) {
    fail("cannot read " + path + ": " + String(error));
  }
}

function validApproval(item: Approval): boolean {
  return (
    item.contentReview === "approved" &&
    item.depictionReview === "approved" &&
    item.ageReview === "approved" &&
    item.rightsReview === "approved" &&
    Boolean(item.titleAr?.trim()) &&
    /^https:\/\//.test(item.reviewEvidenceUrl) &&
    Boolean(item.reviewerId?.trim()) &&
    !Number.isNaN(Date.parse(item.reviewedAt))
  );
}

if (!existsSync(CANDIDATES)) {
  fail("candidate catalog missing. Run npm run sync:kids-youtube first.");
}
if (!existsSync(APPROVALS)) {
  fail("approvals file missing: " + APPROVALS);
}

const candidatePayload = readJson<{ candidates: Candidate[] }>(CANDIDATES);
const approvals = readJson<{ approvals: Approval[] }>(APPROVALS).approvals ?? [];
const approvalMap = new Map(approvals.map((item) => [item.providerVideoId, item]));

const approved = candidatePayload.candidates
  .filter((candidate) => {
    const approval = approvalMap.get(candidate.providerVideoId);
    return candidate.embeddable && Boolean(approval && validApproval(approval));
  })
  .map((candidate) => {
    const approval = approvalMap.get(candidate.providerVideoId)!;
    return {
      id: candidate.id,
      provider: candidate.provider,
      providerVideoId: candidate.providerVideoId,
      titleAr: approval.titleAr,
      titleOriginal: candidate.titleOriginal,
      description: candidate.description,
      publisherName: candidate.publisherName,
      publisherChannelId: candidate.publisherChannelId,
      thumbnailUrl: candidate.thumbnailUrl,
      topic: candidate.topic,
      language: candidate.language,
      ageMin: approval.ageMin,
      ageMax: approval.ageMax,
      durationSeconds: candidate.durationSeconds ?? undefined,
      captionsAvailable: candidate.captionsAvailable,
      embeddable: true,
      sourceUrl: candidate.sourceUrl,
      publishedAt: candidate.publishedAt ?? undefined,
      tags: candidate.tags,
    };
  });

const source = [
  "/** GENERATED by scripts/acquire/promote-kids-media.ts. Do not hand-edit. */",
  'import type { KidsVideo } from "@/visual-golden/services/kids-media/types";',
  "",
  "export const APPROVED_YOUTUBE_KIDS_VIDEOS: KidsVideo[] = " +
    JSON.stringify(approved, null, 2) +
    ";",
  "",
].join("\n");

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, source, "utf-8");

console.log(
  "promote-kids-media PASS:",
  approved.length,
  "approved items ->",
  OUT,
  "| candidates not explicitly approved remain excluded",
);
