import {
  providerResourceEntrySchema,
  rightsLedgerEntrySchema,
  sourceRegistryEntrySchema,
  type ProviderResourceEntry,
  type RightsLedgerEntry,
  type SourceRegistryEntry,
} from "./source-governance";

const CHECKED_AT = "2026-09-24T17:00:00+04:00";

export const sourceRegistry: SourceRegistryEntry[] = sourceRegistryEntrySchema.array().parse([
  {
    sourceId: "src-quran-development-sample",
    title: "عينة القرآن المحلية للتطوير",
    provider: "YaRasoolAllah local development data",
    kind: "internal_development_sample",
    canonicalUrl: null,
    version: "unversioned-development-sample",
    artifactSha256: null,
    checkedAt: CHECKED_AT,
    editorialStatus: "editorial_review_pending",
    notes: "عينة محدودة غير صالحة لتقديم ادعاء متن قرآني كامل أو إصدار إنتاجي.",
  },
  {
    sourceId: "src-tanzil-uthmani-1-1-candidate",
    title: "Tanzil Uthmani Quran Text 1.1 — acquisition candidate",
    provider: "Tanzil",
    kind: "primary_text",
    canonicalUrl: "https://tanzil.net/download/",
    version: "1.1-candidate-not-acquired",
    artifactSha256: null,
    checkedAt: CHECKED_AT,
    editorialStatus: "rights_review_pending",
    notes: "لا يصبح قابلاً للإدخال قبل حفظ شروط المصدر والملف immutable والبصمة والتحقق من 114 سورة.",
  },
  {
    sourceId: "src-library-development-catalog",
    title: "فهرس المكتبة المحلي الأولي",
    provider: "YaRasoolAllah development catalog",
    kind: "catalog_metadata",
    canonicalUrl: null,
    version: "development-catalog-2026-09-23",
    artifactSha256: null,
    checkedAt: CHECKED_AT,
    editorialStatus: "editorial_review_pending",
    notes: "بيانات ببليوغرافية وروابط خارجية فقط؛ لا تثبت حق النسخة أو القراءة أو التنزيل.",
  },
  {
    sourceId: "src-openiti-metadata-candidate",
    title: "OpenITI release metadata — candidate",
    provider: "OpenITI",
    kind: "catalog_metadata",
    canonicalUrl: "https://github.com/OpenITI/RELEASE",
    version: null,
    artifactSha256: null,
    checkedAt: CHECKED_AT,
    editorialStatus: "rights_review_pending",
    notes: "مرشح لسجل الأعمال والنسخ؛ النص الكامل يحتاج مراجعة مستقلة لكل إصدار وعمل.",
  },
  {
    sourceId: "src-openiti-release-pinned",
    title: "OpenITI RELEASE — pinned bibliographic/version metadata",
    provider: "OpenITI",
    kind: "catalog_metadata",
    canonicalUrl:
      "https://github.com/OpenITI/RELEASE/tree/cfc4157a3cf2054c0888f133970a4eaa3e22e58c",
    version: "cfc4157a3cf2054c0888f133970a4eaa3e22e58c",
    artifactSha256: null,
    checkedAt: CHECKED_AT,
    editorialStatus: "verified",
    notes:
      "مرجع مثبت لسجلات الأعمال ومعرفات النسخ الرقمية. التحقق ببليوغرافي فقط؛ النص الكامل والطبعة والحقوق تُراجع لكل نسخة على حدة.",
  },
  {
    sourceId: "src-openiti-historical-texts-pinned",
    title: "OpenITI RELEASE — pinned historical full text",
    provider: "OpenITI",
    kind: "primary_text",
    canonicalUrl:
      "https://github.com/OpenITI/RELEASE/tree/cfc4157a3cf2054c0888f133970a4eaa3e22e58c",
    version: "cfc4157a3cf2054c0888f133970a4eaa3e22e58c",
    artifactSha256: null,
    checkedAt: CHECKED_AT,
    editorialStatus: "verified",
    notes:
      "نصوص OpenITI التاريخية المسجلة هنا مثبتة على إصدار immutable. OpenITI يعلن أن النصوص العربية والفارسية التاريخية المرفوعة والمؤرخة 1900 أو أقدم ضمن الملكية العامة؛ هذا لا يساوي مراجعة علمية أو اعتماد طبعة.",
  },
  {
    sourceId: "src-library-bibliographic-registry",
    title: "Ya Rasool Allah bibliographic work registry",
    provider: "YaRasoolAllah editorial registry",
    kind: "bibliography",
    canonicalUrl: null,
    version: "2026-09-23",
    artifactSha256: null,
    checkedAt: CHECKED_AT,
    editorialStatus: "verified",
    notes:
      "سجل أعمال ونسخ وحالات إتاحة؛ لا يحوّل رابطاً خارجياً إلى حق قراءة أو تنزيل.",
  },
  {
    sourceId: "src-dorar-reference",
    title: "Dorar hadith reference",
    provider: "Dorar",
    kind: "hadith",
    canonicalUrl: "https://dorar.net/hadith",
    version: null,
    artifactSha256: null,
    checkedAt: CHECKED_AT,
    editorialStatus: "rights_review_pending",
    notes: "مرجع تحريري خارجي فقط؛ لا عقد API أو إعادة استخدام أو تخزين للنصوص في هذا الإصدار.",
  },
  {
    sourceId: "src-map-provider-registry",
    title: "Modern map and terrain provider registry",
    provider: "OpenStreetMap / Natural Earth / GeoNames / NASA Earthdata",
    kind: "geodata",
    canonicalUrl: "https://www.openstreetmap.org/copyright",
    version: "provider-policy-2026-09-23",
    artifactSha256: null,
    checkedAt: CHECKED_AT,
    editorialStatus: "rights_review_pending",
    notes:
      "سجل سياسات مرشحة للسياق الجغرافي الحديث فقط؛ لا basemap أو تضاريس مكتسبة، ولا ادعاء مواقع عسكرية تاريخية دقيقة.",
  },
  {
    sourceId: "src-audio-provider-registry",
    title: "Quran audio provider registry",
    provider: "QuranicAudio / EveryAyah / Quran Foundation",
    kind: "audio_recording",
    canonicalUrl: "https://quranicaudio.com/",
    version: "provider-policy-2026-09-23",
    artifactSha256: null,
    checkedAt: CHECKED_AT,
    editorialStatus: "rights_review_pending",
    notes:
      "QuranicAudio رابط خارجي فقط، EveryAyah يحتاج مراجعة ترخيص، وموارد Quran Foundation تخضع لعقد المورد. لا تسجيلات مجمعة.",
  },
  {
    sourceId: "src-aladhan-api",
    title: "AlAdhan prayer-times API and calculation methods",
    provider: "AlAdhan",
    kind: "provider_policy",
    canonicalUrl: "https://aladhan.com/prayer-times-api",
    version: "v1",
    artifactSha256: null,
    checkedAt: CHECKED_AT,
    editorialStatus: "verified",
    notes:
      "تكامل حساب المواقيت القائم؛ يجب إظهار طريقة الحساب ومصدرها وعدم وصف طريقة واحدة بأنها صحيحة عالمياً.",
  },
  {
    sourceId: "src-media-institution-registry",
    title: "Manuscript and historical-media institution candidates",
    provider: "QDL / Gallica / Library of Congress / Internet Archive / Wikimedia Commons / British Library / NYPL",
    kind: "media_catalog",
    canonicalUrl: null,
    version: "candidate-registry-2026-09-23",
    artifactSha256: null,
    checkedAt: CHECKED_AT,
    editorialStatus: "rights_review_pending",
    notes:
      "مؤسسات مرشحة فقط؛ عدد الأصول الإنتاجية المسجلة صفر حتى يكتمل فحص الحقوق على مستوى العنصر.",
  },
  {
    sourceId: "src-children-original-adaptations",
    title: "Platform-original children adaptation registry",
    provider: "YaRasoolAllah editorial studio",
    kind: "educational_adaptation",
    canonicalUrl: null,
    version: "2026-09-23",
    artifactSha256: null,
    checkedAt: CHECKED_AT,
    editorialStatus: "editorial_review_pending",
    notes:
      "مواد أصلية للمنصة مرتبطة بمعرفات مصادر وفئة عمرية، وموسومة صراحة بأنها تكييف تعليمي وليست اقتباساً مباشراً.",
  },
  {
    sourceId: "src-quran-foundation-api",
    title: "Quran Foundation Content API v4",
    provider: "Quran Foundation",
    kind: "primary_text",
    canonicalUrl: "https://api.quran.foundation/content/api/v4",
    version: "v4",
    artifactSha256: null,
    checkedAt: CHECKED_AT,
    editorialStatus: "rights_review_pending",
    notes: "يتطلب مشروع OAuth2 ومفاتيح خادمية وسجل حقوق مستقل لكل مورد ترجمة أو صوت.",
  },
  {
    sourceId: "src-sunnah-api",
    title: "Sunnah.com API",
    provider: "Sunnah.com",
    kind: "hadith",
    canonicalUrl: "https://sunnah.stoplight.io/docs/api/",
    version: null,
    artifactSha256: null,
    checkedAt: CHECKED_AT,
    editorialStatus: "rights_review_pending",
    notes: "المجموعة جزئية؛ يلزم مفتاح API ونسبة الدرجة إلى مقيّم مسمى ومراجعة حقوق الاستخدام.",
  },
  {
    sourceId: "src-tanzil-uthmani-min-1-1-acquired",
    title: "Tanzil Uthmani-min Quran Text 1.1 — acquired immutable artifact",
    provider: "Tanzil",
    kind: "primary_text",
    canonicalUrl: "https://tanzil.net/download/",
    version: "1.1-uthmani-min",
    artifactSha256:
      "2f531f9b1fc886df06297d1a9d5d521fb1fa8a777ca68b3e1cb3e2491fdad6ac",
    checkedAt: CHECKED_AT,
    editorialStatus: "verified",
    notes:
      "نص عربي حرفي مُنزّل ومحفوظ دون تعديل؛ البصمة والعدد (114 سورة / 6236 آية) متحقق منهما آليًا عند الإدخال. التوثيق هنا لسلامة الملف واكتماله، لا لتحقيق علمي للنص.",
  },
]);

export const rightsLedger: RightsLedgerEntry[] = rightsLedgerEntrySchema.array().parse([
  {
    rightsId: "rights-quran-development-sample",
    sourceId: "src-quran-development-sample",
    decision: "development_only",
    licenseName: null,
    licenseUrl: null,
    termsSnapshotPath: null,
    attribution: "YaRasoolAllah development sample",
    permissions: {
      apiAccess: "forbidden",
      caching: "allowed",
      streaming: "forbidden",
      offline: "forbidden",
      redistribution: "forbidden",
      commercial: "forbidden",
    },
    checkedAt: CHECKED_AT,
    reviewNote: "يُمنع الشحن الإنتاجي حتى استبدال العينة بأصل مكتسب ومتحقق منه.",
  },
  {
    rightsId: "rights-tanzil-uthmani-1-1-candidate",
    sourceId: "src-tanzil-uthmani-1-1-candidate",
    decision: "needs_review",
    licenseName: null,
    licenseUrl: "https://tanzil.net/docs/text_license",
    termsSnapshotPath: null,
    attribution: null,
    permissions: {
      apiAccess: "forbidden",
      caching: "unknown",
      streaming: "forbidden",
      offline: "unknown",
      redistribution: "unknown",
      commercial: "unknown",
    },
    checkedAt: CHECKED_AT,
    reviewNote: "لم يُحفظ بعد artifact الرخصة ولا ملف المصدر ولا البصمة؛ بوابة الإدخال مغلقة.",
  },
  {
    rightsId: "rights-library-development-catalog",
    sourceId: "src-library-development-catalog",
    decision: "reference_only",
    licenseName: null,
    licenseUrl: null,
    termsSnapshotPath: null,
    attribution: "External providers remain the rights authorities for each linked item.",
    permissions: {
      apiAccess: "forbidden",
      caching: "forbidden",
      streaming: "forbidden",
      offline: "forbidden",
      redistribution: "forbidden",
      commercial: "forbidden",
    },
    checkedAt: CHECKED_AT,
    reviewNote: "يسمح بعرض الفهرس والرابط الخارجي فقط، ولا يسمح بتنزيل أو قراءة ملف داخل المنصة.",
  },
  {
    rightsId: "rights-openiti-metadata-candidate",
    sourceId: "src-openiti-metadata-candidate",
    decision: "needs_review",
    licenseName: null,
    licenseUrl: null,
    termsSnapshotPath: null,
    attribution: null,
    permissions: {
      apiAccess: "forbidden",
      caching: "unknown",
      streaming: "forbidden",
      offline: "unknown",
      redistribution: "unknown",
      commercial: "unknown",
    },
    checkedAt: CHECKED_AT,
    reviewNote: "يجب تثبيت الإصدار وحفظ شروطه قبل الإدخال؛ لا clearance شاملًا للنصوص الكاملة.",
  },
  {
    rightsId: "rights-openiti-historical-texts-pinned",
    sourceId: "src-openiti-historical-texts-pinned",
    decision: "cleared",
    licenseName: "OpenITI public-domain policy for historical texts dated 1900 or earlier",
    licenseUrl: "https://openiti.org/docs/Copyright_Questions.html",
    termsSnapshotPath: null,
    attribution: "Open Islamicate Texts Initiative (OpenITI), pinned RELEASE commit",
    permissions: {
      apiAccess: "allowed",
      caching: "allowed",
      streaming: "forbidden",
      offline: "unknown",
      redistribution: "allowed",
      commercial: "unknown",
    },
    checkedAt: CHECKED_AT,
    reviewNote:
      "يُسمح بعرض النص التاريخي المثبت من OpenITI داخل القارئ مع الإسناد. لا يشمل ذلك مواد الطبعة الحديثة المحذوفة من corpus، ولا يرفع حالة المراجعة العلمية للعمل.",
  },
  {
    rightsId: "rights-quran-foundation-api",
    sourceId: "src-quran-foundation-api",
    decision: "needs_review",
    licenseName: null,
    licenseUrl: "https://api-docs.quran.foundation/legal/developer-terms/",
    termsSnapshotPath: null,
    attribution: null,
    permissions: {
      apiAccess: "unknown",
      caching: "unknown",
      streaming: "unknown",
      offline: "forbidden",
      redistribution: "forbidden",
      commercial: "unknown",
    },
    checkedAt: CHECKED_AT,
    reviewNote: "المحول غير منفذ والمفاتيح غير مهيأة وشروط كل مورد لم تُسجل بعد.",
  },
  {
    rightsId: "rights-sunnah-api",
    sourceId: "src-sunnah-api",
    decision: "needs_review",
    licenseName: null,
    licenseUrl: null,
    termsSnapshotPath: null,
    attribution: null,
    permissions: {
      apiAccess: "unknown",
      caching: "unknown",
      streaming: "forbidden",
      offline: "forbidden",
      redistribution: "forbidden",
      commercial: "unknown",
    },
    checkedAt: CHECKED_AT,
    reviewNote: "يلزم مفتاح API وقرار حقوق موثق قبل أي استهلاك إنتاجي أو تخزين.",
  },
  {
    rightsId: "rights-tanzil-uthmani-min-1-1",
    sourceId: "src-tanzil-uthmani-min-1-1-acquired",
    decision: "cleared",
    licenseName: "Tanzil Text License (verbatim copies, attribution required)",
    licenseUrl: "https://tanzil.net/docs/text_license",
    termsSnapshotPath: null,
    attribution: "Tanzil Project (tanzil.net)",
    permissions: {
      apiAccess: "forbidden",
      caching: "allowed",
      streaming: "forbidden",
      offline: "allowed",
      redistribution: "allowed",
      commercial: "allowed",
    },
    checkedAt: CHECKED_AT,
    reviewNote:
      "يسمح بالنص الحرفي دون تعديل مع النسبة؛ القرار يغطي النص العربي فقط لا الترجمات.",
  },
]);

export const providerResourceRegistry: ProviderResourceEntry[] =
  providerResourceEntrySchema.array().parse([
    {
      resourceId: "resource-quran-development-sample",
      sourceId: "src-quran-development-sample",
      rightsId: "rights-quran-development-sample",
      provider: "local",
      resourceType: "local_sample",
      integrationMode: "CACHE_ALLOWED",
      endpoint: null,
      acquisitionStatus: "registered",
      credentialsRequired: false,
      credentialsConfigured: false,
      allowedUsages: ["cache"],
      productionReady: false,
    },
    {
      resourceId: "resource-tanzil-uthmani-1-1-candidate",
      sourceId: "src-tanzil-uthmani-1-1-candidate",
      rightsId: "rights-tanzil-uthmani-1-1-candidate",
      provider: "Tanzil",
      resourceType: "file",
      integrationMode: "UNKNOWN_USAGE",
      endpoint: "https://tanzil.net/download/",
      acquisitionStatus: "candidate",
      credentialsRequired: false,
      credentialsConfigured: false,
      allowedUsages: [],
      productionReady: false,
    },
    {
      resourceId: "resource-library-development-catalog",
      sourceId: "src-library-development-catalog",
      rightsId: "rights-library-development-catalog",
      provider: "local",
      resourceType: "catalog",
      integrationMode: "METADATA_ONLY",
      endpoint: null,
      acquisitionStatus: "registered",
      credentialsRequired: false,
      credentialsConfigured: false,
      allowedUsages: ["catalog_metadata", "external_link"],
      productionReady: true,
    },
    {
      resourceId: "resource-openiti-metadata-candidate",
      sourceId: "src-openiti-metadata-candidate",
      rightsId: "rights-openiti-metadata-candidate",
      provider: "OpenITI",
      resourceType: "catalog",
      integrationMode: "METADATA_ONLY",
      endpoint: "https://github.com/OpenITI/RELEASE",
      acquisitionStatus: "candidate",
      credentialsRequired: false,
      credentialsConfigured: false,
      allowedUsages: [],
      productionReady: false,
    },
    {
      resourceId: "resource-openiti-historical-texts-pinned",
      sourceId: "src-openiti-historical-texts-pinned",
      rightsId: "rights-openiti-historical-texts-pinned",
      provider: "OpenITI",
      resourceType: "file",
      integrationMode: "CACHE_ALLOWED",
      endpoint:
        "https://raw.githubusercontent.com/OpenITI/RELEASE/cfc4157a3cf2054c0888f133970a4eaa3e22e58c/",
      acquisitionStatus: "registered",
      credentialsRequired: false,
      credentialsConfigured: false,
      allowedUsages: ["cache", "full_text", "external_link"],
      productionReady: true,
    },
    {
      resourceId: "resource-quran-foundation-api",
      sourceId: "src-quran-foundation-api",
      rightsId: "rights-quran-foundation-api",
      provider: "Quran Foundation",
      resourceType: "api",
      integrationMode: "DIRECT_API",
      endpoint: "https://api.quran.foundation/content/api/v4",
      acquisitionStatus: "candidate",
      credentialsRequired: true,
      credentialsConfigured: false,
      allowedUsages: [],
      productionReady: false,
    },
    {
      resourceId: "resource-sunnah-api",
      sourceId: "src-sunnah-api",
      rightsId: "rights-sunnah-api",
      provider: "Sunnah.com",
      resourceType: "api",
      integrationMode: "DIRECT_API",
      endpoint: "https://sunnah.stoplight.io/docs/api/",
      acquisitionStatus: "candidate",
      credentialsRequired: true,
      credentialsConfigured: false,
      allowedUsages: [],
      productionReady: false,
    },
    {
      resourceId: "resource-tanzil-uthmani-min-1-1",
      sourceId: "src-tanzil-uthmani-min-1-1-acquired",
      rightsId: "rights-tanzil-uthmani-min-1-1",
      provider: "Tanzil",
      resourceType: "file",
      integrationMode: "DOWNLOAD_ALLOWED",
      endpoint: "https://tanzil.net/download/",
      acquisitionStatus: "acquired_immutable",
      credentialsRequired: false,
      credentialsConfigured: false,
      allowedUsages: ["cache", "full_text"],
      productionReady: true,
    },
  ]);

export function getGovernanceRecord(resourceId: string) {
  const resource = providerResourceRegistry.find((item) => item.resourceId === resourceId);
  if (!resource) return null;

  const source = sourceRegistry.find((item) => item.sourceId === resource.sourceId);
  const rights = rightsLedger.find((item) => item.rightsId === resource.rightsId);
  if (!source || !rights) return null;

  return { source, rights, resource };
}

