import {
  providerResourceEntrySchema,
  rightsLedgerEntrySchema,
  sourceRegistryEntrySchema,
  type ProviderResourceEntry,
  type RightsLedgerEntry,
  type SourceRegistryEntry,
} from "./source-governance";

const CHECKED_AT = "2026-09-23T00:00:00+04:00";

export const sourceRegistry: SourceRegistryEntry[] = sourceRegistryEntrySchema.array().parse([
  {
    sourceId: "src-quran-development-sample",
    title: "عينة القرآن المحلية للتطوير",
    provider: "YaRasoolAllah local development data",
    kind: "internal_development_sample",
    canonicalUrl: null,
    version: "unversioned-development-sample",
    artifactSha256: null,
    checkedAt: CHECKED_AT,
    editorialStatus: "editorial_review_pending",
    notes: "عينة محدودة غير صالحة لتقديم ادعاء متن قرآني كامل أو إصدار إنتاجي.",
  },
  {
    sourceId: "src-tanzil-uthmani-1-1-candidate",
    title: "Tanzil Uthmani Quran Text 1.1 — acquisition candidate",
    provider: "Tanzil",
    kind: "primary_text",
    canonicalUrl: "https://tanzil.net/download/",
    version: "1.1-candidate-not-acquired",
    artifactSha256: null,
    checkedAt: CHECKED_AT,
    editorialStatus: "rights_review_pending",
    notes: "لا يصبح قابلاً للإدخال قبل حفظ شروط المصدر والملف immutable والبصمة والتحقق من 114 سورة.",
  },
  {
    sourceId: "src-library-development-catalog",
    title: "فهرس المكتبة المحلي الأولي",
    provider: "YaRasoolAllah development catalog",
    kind: "catalog_metadata",
    canonicalUrl: null,
    version: "development-catalog-2026-09-23",
    artifactSha256: null,
    checkedAt: CHECKED_AT,
    editorialStatus: "editorial_review_pending",
    notes: "بيانات ببليوغرافية وروابط خارجية فقط؛ لا تثبت حق النسخة أو القراءة أو التنزيل.",
  },
  {
    sourceId: "src-openiti-metadata-candidate",
    title: "OpenITI release metadata — candidate",
    provider: "OpenITI",
    kind: "catalog_metadata",
    canonicalUrl: "https://github.com/OpenITI/RELEASE",
    version: null,
    artifactSha256: null,
    checkedAt: CHECKED_AT,
    editorialStatus: "rights_review_pending",
    notes: "مرشح لسجل الأعمال والنسخ؛ النص الكامل يحتاج مراجعة مستقلة لكل إصدار وعمل.",
  },
  {
    sourceId: "src-quran-foundation-api",
    title: "Quran Foundation Content API v4",
    provider: "Quran Foundation",
    kind: "primary_text",
    canonicalUrl: "https://api.quran.foundation/content/api/v4",
    version: "v4",
    artifactSha256: null,
    checkedAt: CHECKED_AT,
    editorialStatus: "rights_review_pending",
    notes: "يتطلب مشروع OAuth2 ومفاتيح خادمية وسجل حقوق مستقل لكل مورد ترجمة أو صوت.",
  },
  {
    sourceId: "src-sunnah-api",
    title: "Sunnah.com API",
    provider: "Sunnah.com",
    kind: "hadith",
    canonicalUrl: "https://sunnah.stoplight.io/docs/api/",
    version: null,
    artifactSha256: null,
    checkedAt: CHECKED_AT,
    editorialStatus: "rights_review_pending",
    notes: "المجموعة جزئية؛ يلزم مفتاح API ونسبة الدرجة إلى مقيّم مسمى ومراجعة حقوق الاستخدام.",
  },
  {
    sourceId: "src-tanzil-uthmani-min-1-1-acquired",
    title: "Tanzil Uthmani-min Quran Text 1.1 — acquired immutable artifact",
    provider: "Tanzil",
    kind: "primary_text",
    canonicalUrl: "https://tanzil.net/download/",
    version: "1.1-uthmani-min",
    artifactSha256:
      "2f531f9b1fc886df06297d1a9d5d521fb1fa8a777ca68b3e1cb3e2491fdad6ac",
    checkedAt: CHECKED_AT,
    editorialStatus: "verified",
    notes:
      "نص عربي حرفي مُنزّل ومحفوظ دون تعديل؛ البصمة والعدد (114 سورة / 6236 آية) متحقق منهما آليًا عند الإدخال. التوثيق هنا لسلامة الملف واكتماله، لا لتحقيق علمي للنص.",
  },
]);

export const rightsLedger: RightsLedgerEntry[] = rightsLedgerEntrySchema.array().parse([
  {
    rightsId: "rights-quran-development-sample",
    sourceId: "src-quran-development-sample",
    decision: "development_only",
    licenseName: null,
    licenseUrl: null,
    termsSnapshotPath: null,
    attribution: "YaRasoolAllah development sample",
    permissions: {
      apiAccess: "forbidden",
      caching: "allowed",
      streaming: "forbidden",
      offline: "forbidden",
      redistribution: "forbidden",
      commercial: "forbidden",
    },
    checkedAt: CHECKED_AT,
    reviewNote: "يُمنع الشحن الإنتاجي حتى استبدال العينة بأصل مكتسب ومتحقق منه.",
  },
  {
    rightsId: "rights-tanzil-uthmani-1-1-candidate",
    sourceId: "src-tanzil-uthmani-1-1-candidate",
    decision: "needs_review",
    licenseName: null,
    licenseUrl: "https://tanzil.net/docs/text_license",
    termsSnapshotPath: null,
    attribution: null,
    permissions: {
      apiAccess: "forbidden",
      caching: "unknown",
      streaming: "forbidden",
      offline: "unknown",
      redistribution: "unknown",
      commercial: "unknown",
    },
    checkedAt: CHECKED_AT,
    reviewNote: "لم يُحفظ بعد artifact الرخصة ولا ملف المصدر ولا البصمة؛ بوابة الإدخال مغلقة.",
  },
  {
    rightsId: "rights-library-development-catalog",
    sourceId: "src-library-development-catalog",
    decision: "reference_only",
    licenseName: null,
    licenseUrl: null,
    termsSnapshotPath: null,
    attribution: "External providers remain the rights authorities for each linked item.",
    permissions: {
      apiAccess: "forbidden",
      caching: "forbidden",
      streaming: "forbidden",
      offline: "forbidden",
      redistribution: "forbidden",
      commercial: "forbidden",
    },
    checkedAt: CHECKED_AT,
    reviewNote: "يسمح بعرض الفهرس والرابط الخارجي فقط، ولا يسمح بتنزيل أو قراءة ملف داخل المنصة.",
  },
  {
    rightsId: "rights-openiti-metadata-candidate",
    sourceId: "src-openiti-metadata-candidate",
    decision: "needs_review",
    licenseName: null,
    licenseUrl: null,
    termsSnapshotPath: null,
    attribution: null,
    permissions: {
      apiAccess: "forbidden",
      caching: "unknown",
      streaming: "forbidden",
      offline: "unknown",
      redistribution: "unknown",
      commercial: "unknown",
    },
    checkedAt: CHECKED_AT,
    reviewNote: "يجب تثبيت الإصدار وحفظ شروطه قبل الإدخال؛ لا clearance شاملًا للنصوص الكاملة.",
  },
  {
    rightsId: "rights-quran-foundation-api",
    sourceId: "src-quran-foundation-api",
    decision: "needs_review",
    licenseName: null,
    licenseUrl: "https://api-docs.quran.foundation/legal/developer-terms/",
    termsSnapshotPath: null,
    attribution: null,
    permissions: {
      apiAccess: "unknown",
      caching: "unknown",
      streaming: "unknown",
      offline: "forbidden",
      redistribution: "forbidden",
      commercial: "unknown",
    },
    checkedAt: CHECKED_AT,
    reviewNote: "المحول غير منفذ والمفاتيح غير مهيأة وشروط كل مورد لم تُسجل بعد.",
  },
  {
    rightsId: "rights-sunnah-api",
    sourceId: "src-sunnah-api",
    decision: "needs_review",
    licenseName: null,
    licenseUrl: null,
    termsSnapshotPath: null,
    attribution: null,
    permissions: {
      apiAccess: "unknown",
      caching: "unknown",
      streaming: "forbidden",
      offline: "forbidden",
      redistribution: "forbidden",
      commercial: "unknown",
    },
    checkedAt: CHECKED_AT,
    reviewNote: "يلزم مفتاح API وقرار حقوق موثق قبل أي استهلاك إنتاجي أو تخزين.",
  },
  {
    rightsId: "rights-tanzil-uthmani-min-1-1",
    sourceId: "src-tanzil-uthmani-min-1-1-acquired",
    decision: "cleared",
    licenseName: "Tanzil Text License (verbatim copies, attribution required)",
    licenseUrl: "https://tanzil.net/docs/text_license",
    termsSnapshotPath: null,
    attribution: "Tanzil Project (tanzil.net)",
    permissions: {
      apiAccess: "forbidden",
      caching: "allowed",
      streaming: "forbidden",
      offline: "allowed",
      redistribution: "allowed",
      commercial: "allowed",
    },
    checkedAt: CHECKED_AT,
    reviewNote:
      "يسمح بالنص الحرفي دون تعديل مع النسبة؛ القرار يغطي النص العربي فقط لا الترجمات.",
  },
]);

export const providerResourceRegistry: ProviderResourceEntry[] =
  providerResourceEntrySchema.array().parse([
    {
      resourceId: "resource-quran-development-sample",
      sourceId: "src-quran-development-sample",
      rightsId: "rights-quran-development-sample",
      provider: "local",
      resourceType: "local_sample",
      endpoint: null,
      acquisitionStatus: "registered",
      credentialsRequired: false,
      credentialsConfigured: false,
      allowedUsages: ["cache"],
      productionReady: false,
    },
    {
      resourceId: "resource-tanzil-uthmani-1-1-candidate",
      sourceId: "src-tanzil-uthmani-1-1-candidate",
      rightsId: "rights-tanzil-uthmani-1-1-candidate",
      provider: "Tanzil",
      resourceType: "file",
      endpoint: "https://tanzil.net/download/",
      acquisitionStatus: "candidate",
      credentialsRequired: false,
      credentialsConfigured: false,
      allowedUsages: [],
      productionReady: false,
    },
    {
      resourceId: "resource-library-development-catalog",
      sourceId: "src-library-development-catalog",
      rightsId: "rights-library-development-catalog",
      provider: "local",
      resourceType: "catalog",
      endpoint: null,
      acquisitionStatus: "registered",
      credentialsRequired: false,
      credentialsConfigured: false,
      allowedUsages: ["catalog_metadata", "external_link"],
      productionReady: true,
    },
    {
      resourceId: "resource-openiti-metadata-candidate",
      sourceId: "src-openiti-metadata-candidate",
      rightsId: "rights-openiti-metadata-candidate",
      provider: "OpenITI",
      resourceType: "catalog",
      endpoint: "https://github.com/OpenITI/RELEASE",
      acquisitionStatus: "candidate",
      credentialsRequired: false,
      credentialsConfigured: false,
      allowedUsages: [],
      productionReady: false,
    },
    {
      resourceId: "resource-quran-foundation-api",
      sourceId: "src-quran-foundation-api",
      rightsId: "rights-quran-foundation-api",
      provider: "Quran Foundation",
      resourceType: "api",
      endpoint: "https://api.quran.foundation/content/api/v4",
      acquisitionStatus: "candidate",
      credentialsRequired: true,
      credentialsConfigured: false,
      allowedUsages: [],
      productionReady: false,
    },
    {
      resourceId: "resource-sunnah-api",
      sourceId: "src-sunnah-api",
      rightsId: "rights-sunnah-api",
      provider: "Sunnah.com",
      resourceType: "api",
      endpoint: "https://sunnah.stoplight.io/docs/api/",
      acquisitionStatus: "candidate",
      credentialsRequired: true,
      credentialsConfigured: false,
      allowedUsages: [],
      productionReady: false,
    },
    {
      resourceId: "resource-tanzil-uthmani-min-1-1",
      sourceId: "src-tanzil-uthmani-min-1-1-acquired",
      rightsId: "rights-tanzil-uthmani-min-1-1",
      provider: "Tanzil",
      resourceType: "file",
      endpoint: "https://tanzil.net/download/",
      acquisitionStatus: "acquired_immutable",
      credentialsRequired: false,
      credentialsConfigured: false,
      allowedUsages: ["cache", "full_text"],
      productionReady: true,
    },
  ]);

export function getGovernanceRecord(resourceId: string) {
  const resource = providerResourceRegistry.find((item) => item.resourceId === resourceId);
  if (!resource) return null;

  const source = sourceRegistry.find((item) => item.sourceId === resource.sourceId);
  const rights = rightsLedger.find((item) => item.rightsId === resource.rightsId);
  if (!source || !rights) return null;

  return { source, rights, resource };
}

