/**
 * Ingests the staged Tanzil artifact into a typed, checksummed corpus module.
 *
 * Input (immutable, never modified):
 *   data-sources/tanzil/quran-uthmani-min-1.1.txt  (`sura|aya|text` rows)
 * Output (generated, do not hand-edit):
 *   client/src/data/quranCorpus.ts
 *
 * Validation gates (any failure aborts with non-zero exit):
 *   - artifact SHA-256 matches the recorded acquisition hash
 *   - exactly 114 surahs, sequential ayah numbers, 6236 verses total
 *   - per-surah ayah counts reconcile with the app chapter metadata
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
// Chapter metadata is the app's live single source of truth; the artifact
// must reconcile against it (import is side-effect free).
import { getQuranChapters } from "../client/src/services/quranService";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const ARTIFACT = resolve(root, "data-sources/tanzil/quran-uthmani-min-1.1.txt");
const EXPECTED_SHA256 =
  "2F531F9B1FC886DF06297D1A9D5D521FB1FA8A777CA68B3E1CB3E2491FDAD6AC";
const OUT = resolve(root, "client/src/data/quranCorpus.ts");

function fail(message: string): never {
  console.error(`ingest-tanzil-quran FAILED: ${message}`);
  process.exit(1);
}

const raw = readFileSync(ARTIFACT, "utf-8");
const actualSha = createHash("sha256").update(raw, "utf-8").digest("hex");
if (actualSha.toLowerCase() !== EXPECTED_SHA256.toLowerCase()) {
  fail(`artifact checksum mismatch (got ${actualSha})`);
}

const verses = new Map<string, string>();
const counts = new Map<number, number>();
for (const line of raw.split("\n")) {
  const trimmed = line.replace(/\r$/, "");
  if (!trimmed || trimmed.startsWith("#")) continue;
  const sep1 = trimmed.indexOf("|");
  const sep2 = trimmed.indexOf("|", sep1 + 1);
  if (sep1 < 0 || sep2 < 0) fail(`malformed row: ${trimmed.slice(0, 60)}`);
  const surah = Number(trimmed.slice(0, sep1));
  const ayah = Number(trimmed.slice(sep1 + 1, sep2));
  const text = trimmed.slice(sep2 + 1);
  if (!text) fail(`empty text at ${surah}:${ayah}`);
  const key = `${surah}:${ayah}`;
  if (verses.has(key)) fail(`duplicate verse key ${key}`);
  verses.set(key, text);
  counts.set(surah, (counts.get(surah) ?? 0) + 1);
  const expectedAyah = counts.get(surah)!;
  if (ayah !== expectedAyah) fail(`non-sequential ayah at ${key}`);
}

if (counts.size !== 114) fail(`expected 114 surahs, got ${counts.size}`);
if (verses.size !== 6236) fail(`expected 6236 verses, got ${verses.size}`);
const chapters = await getQuranChapters();
for (const ch of chapters) {
  const got = counts.get(ch.number) ?? 0;
  if (got !== ch.ayahCount) {
    fail(`surah ${ch.number}: artifact has ${got}, metadata expects ${ch.ayahCount}`);
  }
}

const entries = [...verses.entries()]
  .map(([key, text]) => `  ${JSON.stringify(key)}: ${JSON.stringify(text)},`)
  .join("\n");

const out = `/**
 * GENERATED by scripts/ingest-tanzil-quran.ts — do not hand-edit.
 *
 * Verbatim Tanzil Uthmani-min v1.1 Arabic text (CC-style verbatim terms,
 * modification forbidden). SHA-256 of source artifact:
 * ${EXPECTED_SHA256}
 * In-app attribution: النص القرآني: مشروع تنزيل (tanzil.net).
 * 114 surahs / 6236 verses, reconciled against chapter metadata.
 */
export const QURAN_SOURCE = {
  provider: "Tanzil",
  textType: "uthmani-min",
  version: "1.1",
  artifactSha256: ${JSON.stringify(EXPECTED_SHA256)},
  termsUrl: "https://tanzil.net/docs/Text_License",
  attributionAr: "النص القرآني: مشروع تنزيل (tanzil.net)",
  surahCount: 114,
  verseCount: ${verses.size},
} as const;

export const UTHMANI_VERSES: Record<string, string> = {
${entries}
};
`;

writeFileSync(OUT, out, "utf-8");
console.log(
  `ingest-tanzil-quran PASS: ${verses.size} verses, ${counts.size} surahs -> client/src/data/quranCorpus.ts`,
);
